version: 2

workflows:
  version: 2
  default:
    jobs:
      - "python-2.7"
      - "linting"

default-job: &default-job
  docker:
    - image: conda/miniconda3:latest
  steps:
    - checkout
    - restore_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
    - run:
        name: Install conda environment
        command: .circleci/install.sh
    - run:
        name: Running checks
        command: .circleci/${TEST_SCRIPT}
    - save_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - "/usr/local/envs/${ENV_NAME}/"
          - "/usr/local/pkgs"

jobs:
  "python-2.7":
    <<: *default-job
    environment:
      PYTHON: "2.7"
      ENV_NAME: "pyreshaper-2.7"
      TEST_SCRIPT: "test.sh"

  "linting":
    <<: *default-job
    environment:
      PYTHON: "2.7"
      ENV_NAME: "pyreshaper-2.7"
      TEST_SCRIPT: "lint.sh"
